### ISSUE TITLE
Replace dependency version

### ISSUE THREAD

**Issue by rafaldziuryk** [rubiconba/fastlane-plugin-flutter-version-manager#2]
Hi,

in pubspec.yaml if we have same version for app and dev-dependencies (or dependencies probably), action `apply_new_version` replace also version number in deps

```
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  test_coverage: 0.5.0

dev_dependencies:
  flutter_coverage_badge: 0.0.1+1
  flutter_test:
    sdk: flutter
```

is replaced by:

```
version: 0.0.1+7860469

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  test_coverage: 0.5.0

dev_dependencies:
  flutter_coverage_badge: 0.0.1+7860469 // SHOULD STAY 1 <<-----------------
  flutter_test:
    sdk: flutter
```
